spring:
    datasource:
        url: jdbc:mysql://localhost:3306/hibernate-masterclass?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                show_sql: false
                format_sql: false
                use_sql_comments: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                id:
                    new_generator_mappings: false
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update