spring:
    datasource:
        url: jdbc:mysql://localhost:3306/hibernate-masterclass?useSSL=false&serverTimezone=UTC
        username: hbstudent
        password: hbstudent
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
        ddl-auto: update
        show-sql: true


