spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
      defer-datasource-initialization: true
server:
  port: 8081
